spring.application.name=Automation_Timesheet

timesheet.username=103809
timesheet.password=Madhukiran@23
timesheet.url=https://timesheet.inspirisys.com/Security/Login.aspx

# PALEPU MADHU kIRAN
#timesheet.ddl.projectname=JKGB RRB Amalgamation
#timesheet.ddl.milestone=Data Migration
#timesheet.ddl.taskgroup=Support
#timesheet.ddl.taskname=Support
#timesheet.txt.taskdesc=Supporting for loan migration.
#timesheet.ddl.taskhours=8
#timesheet.ddl.taskminutes=0

timesheet.ddl.projectname=JKGB RRB Amalgamation
timesheet.ddl.milestone=Data Migration
timesheet.ddl.taskgroup=Support
timesheet.ddl.taskname=Support
timesheet.txt.taskdesc=Supporting for loan migration.
timesheet.ddl.taskhours=8
timesheet.ddl.taskminutes=0
