spring.application.name=Automation_Timesheet

timesheet.username=103809
timesheet.password=Madhukiran@23
timesheet.url=https://timesheet.inspirisys.com/Security/Login.aspx

timesheet.ddlProjectname=1239
timesheet.ddlmilestone=12515
timesheet.ddltask_group=1563
timesheet.ddltask_name=2195
timesheet.txtTask_Desc=Supporting for loan migration.
timesheet.ddlTask_Hours=9
timesheet.ddlTaskminutes=1